disabled_rules:
  - trailing_whitespace
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - /Pods
  - Pods/
file_length:
  warning: 300
  error: 350
identifier_name:
  min_length: 2
line_length:
  warning: 150
  error: 160
