excluded: # paths to ignore during linting. Takes precedence over `included`.
    - Pods
    - /Pods
    - Pods/
    - Carthage
    - SwiftLint/Common/3rdPartyLib
file_length:
    warning: 300
    error: 350
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true
identifier_name:
    min_length: 2
line_length:
    warning: 150
    error: 160
function_body_length:
    warning: 300
    error: 500
function_parameter_count:
    warning: 6
    error: 8
type_body_length:
    warning: 300
    error: 500
file_length:
    warning: 1000
    error: 1500
    ignore_comment_only_lines: true
cyclomatic_complexity:
    warning: 15
    error: 25
reporter: "xcode"

