# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'FightAcademy' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Firebase/Analytics'
  pod 'SwiftLint'
  pod 'FSCalendar'
  pod 'NVActivityIndicatorView'
  pod 'SwiftMessages'
  pod 'SwiftGen'
  pod 'Firebase/RemoteConfig'

  # Pods for FightAcademy

  target 'FightAcademyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FightAcademyUITests' do
    # Pods for testing
  end

end
